
# docker build -t steenhansen/sff-audio-kube:update-nodejs .    --no-cache

# docker push steenhansen/sff-audio-kube:update-nodejs

FROM steenhansen/sff-audio-kube:base-nodejs

CMD ["node", "/nodejs-base/web-app/update__db/cron-server-81.js"]

