apiVersion: v1
kind: Service
metadata:
  name: neo4j--db--service    # NB this value is used in neo4j-databse.js to access Neo4j database
  labels:
    app: neo4j--db--app         
spec:
  type: LoadBalancer
  ports:
  - name: neo4j--ports
    port: 7474
    targetPort: 7474
  - name: bolt--ports
    port: 7687
    targetPort: 7687
  selector:
    app: neo4j--db--app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j--db--service
  labels:
    app: neo4j--db--app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j--db--app
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: neo4j--db--app
    spec:
      containers:
      - image: steenhansen/sff-audio-kube:small-neo4j
        name: neo4j--database 
        imagePullPolicy: Always
        env:
        - name: INIT_NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j--db--secret
              key: INIT_NEO4J_PASSWORD
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo4j--db--secret
              key: NEO4J_AUTH
        - name: NEO4J_USERNAME
          valueFrom:
            secretKeyRef:
              name: neo4j--db--secret
              key: NEO4J_USERNAME      
        ports:
        - containerPort: 7474
        - containerPort: 7687
        envFrom:
        - configMapRef:
            name: env--vars--config
        volumeMounts:
        - name: neo4j--persistent--storage
          mountPath: /var/lib/neo4j/data/
      volumes:
      - name: neo4j--persistent--storage
        persistentVolumeClaim:
          claimName: persistant--volume--claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistant--volume--claim
  labels:
    app: neo4j--db--app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
