# https://www.base64decode.org/

apiVersion: v1
kind: Secret
metadata:
  name: neo4j--db--secret
data:
  NEO4J_AUTH: bmVvNGoveWVyX3Bhc3N3b3Jk
  NEO4J_USERNAME: bmVvNGo= 
  INIT_NEO4J_PASSWORD: eWVyX3Bhc3N3b3Jk
#                      eWVyX3Bhc3N3b3Jk == yer_password

