var mock_data_return =  [
 {
  "episode number": "134",
  "publish date": "2018-08-29 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-134-the-tyger-by-william-blake/",
  "hh:mm:ss": "0:28:39",
  "file name": "rsd134TheTyger.mp3",
  "byte size": "28,333,002",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Tyger",
  "book author": "William Blake",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/TheTygerByWilliamBlakeSongsOfInnoncence1826.pdf",
  "video link": "",
  "podcast description": "The Tyger by William Blake"
 },
 {
  "episode number": "133",
  "publish date": "2018-08-22 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-133-the-king-of-the-mazy-may-by-jack-london/",
  "hh:mm:ss": "0:30:29",
  "file name": "rsd133TheKingOfMazyMay.mp3",
  "byte size": "30,094,986",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The King Of The Mazy May",
  "book author": "Jack London",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheKingOfTheMazyMayByJackLondonYouthsCompanionNov301899.pdf",
  "video link": "",
  "podcast description": "The King Of The Mazy May by Jack London"
 },
 {
  "episode number": "132",
  "publish date": "2018-08-15 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-132-wow-by-william-seabrook/",
  "hh:mm:ss": "0:29:51",
  "file name": "rsd132Wow.mp3",
  "byte size": "29,487,882",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Wow!",
  "book author": "William Seabrook",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/WowByWilliamSeabrook.pdf",
  "video link": "",
  "podcast description": "Wow! by William Seabrook"
 },
 {
  "episode number": "131",
  "publish date": "2018-08-08 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-131-a-thunderstorm-by-archibald-lampman/",
  "hh:mm:ss": "0:34:31",
  "file name": "rsd131AThunderstorm.mp3",
  "byte size": "33,959,370",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "A Thunderstorm",
  "book author": "Archibald Lampman",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/AThunderstormByArchibaldLampman.pdf",
  "video link": "",
  "podcast description": "A Thunderstorm by Archibald Lampman"
 },
 {
  "episode number": "130",
  "publish date": "2018-08-01 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-130-the-apparition-in-the-prize-ring-by-robert-e-howard/",
  "hh:mm:ss": "0:33:15",
  "file name": "rsd130TheApparition.mp3",
  "byte size": "32,744,010",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Apparition In The Prize Ring",
  "book author": "Robert E. Howard",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheApparitionInThePrizeRingByRobertE.Howard.pdf",
  "video link": "",
  "podcast description": "The Apparition In The Prize Ring by Robert E. Howard"
 },
 {
  "episode number": "129",
  "publish date": "2018-07-25 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-129-sadastor-by-clark-ashton-smith/",
  "hh:mm:ss": "0:34:31",
  "file name": "rsd129Sadastor.mp3",
  "byte size": "33,955,338",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Sadastor",
  "book author": "Clark Ashton Smith",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/can-pdfs/SadastorByClarkAshtonSmith.pdf",
  "video link": "",
  "podcast description": "Sadastor by Clark Ashton Smith"
 },
 {
  "episode number": "128",
  "publish date": "2018-07-18 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-128-the-leather-funnel-by-sir-arthur-conan-doyle/",
  "hh:mm:ss": "0:31:28",
  "file name": "rsd128TheLeatherFunnel.mp3",
  "byte size": "31,038,474",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Leather Funnel",
  "book author": "Sir Arthur Conan Doyle",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheLeatherFunnelBySirArthurConanDoyleMCCLURESNov1902.pdf",
  "video link": "",
  "podcast description": "The Leather Funnel by Sir Arthur Conan Doyle"
 },
 {
  "episode number": "127",
  "publish date": "2018-07-11 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-127-darkness-by-lord-byron/",
  "hh:mm:ss": "0:32:20",
  "file name": "rsd127Darkness.mp3",
  "byte size": "31,861,002",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Darkness",
  "book author": "Lord Byron",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/DarknessByLordByron.pdf",
  "video link": "",
  "podcast description": "Darkness by Lord Byron"
 },
 {
  "episode number": "126",
  "publish date": "2018-07-03 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-126-the-wonderful-tar-baby-story-and-how-mr-rabbit-was-too-sharp-for-mr-fox-by-joel-chandler-harris/",
  "hh:mm:ss": "0:35:01",
  "file name": "rsd126TheWonderfulTarBaby.mp3",
  "byte size": "34,442,058",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Wonderful Tar Baby Story and How Mr. Rabbit Was Too Sharp For Mr. Fox",
  "book author": "Joel Chandler Harris",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/WonderfulTarBabyStoryHowMr.RabbitWasTooSharpForMrFoxByJoelChandlerHarris.pdf",
  "video link": "",
  "podcast description": "Wonderful Tar Baby Story and How Mr. Rabbit Was Too Sharp For Mr. Fox by Joel Chandler Harris"
 },
 {
  "episode number": "125",
  "publish date": "2018-06-27 00:01",
  "post link": "https://www.sffaudio.com/reading-short-and-deep-125-the-dancing-partner-by-jerome-k-jerome/",
  "hh:mm:ss": "0:30:30",
  "file name": "rsd125TheDancingPartner.mp3",
  "byte size": "30,108,810",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Dancing-Partner",
  "book author": "Jerome K. Jerome",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheDancingPartnerByJeromeK.Jerome.pdf",
  "video link": "",
  "podcast description": "The Dancing-Partner by Jerome K. Jerome"
 },
 {
  "episode number": "124",
  "publish date": "2018-06-20 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-124-the-treasure-in-the-forest-by-h-g-wells/",
  "hh:mm:ss": "0:30:42",
  "file name": "rsd124TheTreasureInTheForest.mp3",
  "byte size": "30,293,130",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Treasure In The Forest",
  "book author": "H.G. Wells",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheTreasureInTheForestByH.G.WellsWWA.pdf",
  "video link": "",
  "podcast description": "The Treasure In The Forest by H.G. Wells"
 },
 {
  "episode number": "123",
  "publish date": "2018-06-13 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-123-remarkable-story-of-chicken-little-by-anonymous/",
  "hh:mm:ss": "0:28:45",
  "file name": "rsd123ChickenLittle.mp3",
  "byte size": "28,427,466",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Remarkable Story Of Chicken Little",
  "book author": "Anonymous",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/RemarkableStoryOfChickenLittle.pdf",
  "video link": "",
  "podcast description": "Remarkable Story Of Chicken Little by Anonymous"
 },
 {
  "episode number": "122",
  "publish date": "2018-06-06 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-122-displaced-person-by-eric-frank-russell/",
  "hh:mm:ss": "0:31:25",
  "file name": "rsd122DisplacedPerson.mp3",
  "byte size": "30,985,482",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Displaced Person",
  "book author": "Eric Frank Russell",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/DisplacedPersonByEricFrankRussellWT.pdf",
  "video link": "",
  "podcast description": "Displaced Person by Eric Frank Russell"
 },
 {
  "episode number": "121",
  "publish date": "2018-05-30 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-121-the-lottery-by-shirley-jackson/",
  "hh:mm:ss": "0:34:04",
  "file name": "rsd121TheLottery.mp3",
  "byte size": "33,537,738",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Lottery",
  "book author": "Shirley Jackson",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/can-pdfs/TheLotteryByShirleyJackson5thFontanaBookOfHorrorStories.pdf",
  "video link": "",
  "podcast description": "The Lottery by Shirley Jackson"
 },
 {
  "episode number": "120",
  "publish date": "2018-05-23 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-120-sis-beckys-pickaninny-by-charles-w-chestnutt/",
  "hh:mm:ss": "0:31:15",
  "file name": "rsd120SisBeckys.mp3",
  "byte size": "30,836,298",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Sis' Becky's Pickaninny",
  "book author": "Charles W. Chestnutt",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/SisBeckysPickaninnyByCharlesW.Chestnutt.pdf",
  "video link": "",
  "podcast description": "Sis' Becky's Pickaninny by Charles W. Chesnutt"
 },
 {
  "episode number": "119",
  "publish date": "2018-05-16 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-119-the-thing-in-the-cellar-by-david-h-keller/",
  "hh:mm:ss": "0:34:22",
  "file name": "rsd119TheThingInTheCellar.mp3",
  "byte size": "33,823,434",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Thing In The Cellar",
  "book author": "Davis H. Keller",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/can-pdfs/TheThingInTheCellarByDavidH.Keller.pdf",
  "video link": "",
  "podcast description": "The Thing In The Cellar by David H. Keller"
 },
 {
  "episode number": "118",
  "publish date": "2018-05-09 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-118-unda-or-the-bride-of-the-sea-by-h-p-lovecraft/",
  "hh:mm:ss": "0:36:23",
  "file name": "rsd118Unda.mp3",
  "byte size": "35,762,250",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Unda; or The Bride Of The Sea",
  "book author": "H.P. Lovecraft",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/UndaOrTheBrideOfTheSeaByH.P.Lovecraft.pdf",
  "video link": "",
  "podcast description": "Unda; or The Bride Of The Sea by H.P. Lovecraft"
 },
 {
  "episode number": "117",
  "publish date": "2018-05-02 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-117-the-bed-of-shadows-by-fred-r-farrow/",
  "hh:mm:ss": "0:31:43",
  "file name": "rsd117BedOfShadows.mp3",
  "byte size": "31,286,730",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Bed Of Shadow",
  "book author": "Fred R. Farrow",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/StrephonAndChloeByJonathanSwift.pdf",
  "video link": "",
  "podcast description": "The Bed Of Shadow by Fred R. Farrow"
 },
 {
  "episode number": "116",
  "publish date": "2018-04-25 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-116-strephon-and-chloe-by-jonathan-swift/",
  "hh:mm:ss": "0:34:20",
  "file name": "rsd116StrephonAndChloe.mp3",
  "byte size": "33,788,874",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Strephon And Chloe",
  "book author": "Jonathan Swift",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/StrephonAndChloeByJonathanSwift.pdf",
  "video link": "",
  "podcast description": "Strephon And Chloe by Jonathan Swift"
 },
 {
  "episode number": "115",
  "publish date": "2018-04-18 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-115-the-secret-of-the-machines-by-rudyard-kipling/",
  "hh:mm:ss": "0:31:52",
  "file name": "rsd115TheSecretOfTheMachines.mp3",
  "byte size": "31,416,330",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Secret Of the Machines",
  "book author": "Rudyard Kipling",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/TheSecretOfTheMachinesByRudyardKipling.pdf",
  "video link": "",
  "podcast description": "The Secret Of the Machines by Rudyard Kipling"
 },
 {
  "episode number": "114",
  "publish date": "2018-04-11 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-114-hunting-the-deceitful-turkey-by-mark-twain/",
  "hh:mm:ss": "0:32:43",
  "file name": "rsd114HuntingTheDeceitfulTurkey.mp3",
  "byte size": "32,234,250",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Hunting The Deceitful Turkey",
  "book author": "Mark Twain",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/HuntingTheDeceitfulTurkeyByMarkTwainHAPERSDec1906.pdf",
  "video link": "",
  "podcast description": "Hunting The Deceitful Turkey by Mark Twain"
 },
 {
  "episode number": "113",
  "publish date": "2018-04-04 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-113-extraterrestrial-trilogue-on-terran-self-destruction-by-sheri-s-tepper/",
  "hh:mm:ss": "0:32:30",
  "file name": "rsd113ExtraterrestrialTrilogue.mp3",
  "byte size": "32,031,498",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Extraterrestrial Trilogue On Terran Self-Destruction",
  "book author": "Sheri S. Tepper",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/ExtraterrestrialTrilogueOnTerranSelfDestructionBySheriS.Tepper.pdf",
  "video link": "",
  "podcast description": "Extraterrestrial Trilogue On Terran Self-Destruction by Sheri S. Tepper"
 },
 {
  "episode number": "112",
  "publish date": "2018-03-28 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-112-the-perfect-woman-by-robert-sheckley/",
  "hh:mm:ss": "0:35:13",
  "file name": "rsd112ThePerfectWoman.mp3",
  "byte size": "34,632,714",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Perfect Woman",
  "book author": "Robert Sheckley",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/ThePerfectWomanByRobertSheckley.pdf",
  "video link": "",
  "podcast description": "The Pertfect Woman by Robert Sheckley"
 },
 {
  "episode number": "111",
  "publish date": "2018-03-21 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-111-hall-of-mirrors-by-fredric-brown/",
  "hh:mm:ss": "0:33:39",
  "file name": "rsd111HallOfMirrors.mp3",
  "byte size": "33,135,690",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Hall Of Mirrors",
  "book author": "Fredric Brown",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/HallOfMirrorsByFredricBrown.pdf",
  "video link": "",
  "podcast description": "Hall Of Mirrors by Fredric Brown"
 },
 {
  "episode number": "110",
  "publish date": "2018-03-14 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-110-christmas-eve-by-guy-de-maupassant/",
  "hh:mm:ss": "0:33:44",
  "file name": "rsd110ChristmasEve.mp3",
  "byte size": "33,216,906",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Christmas Eve",
  "book author": "Guy de Maupassant",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/ChristmasEveByGuyDeMaupassant.pdf",
  "video link": "",
  "podcast description": "Christmas Eve by Guy de Maupassant"
 },
 {
  "episode number": "109",
  "publish date": "2018-03-07 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-108-the-angry-street-a-bad-dream-by-g-k-chesterton/",
  "hh:mm:ss": "0:31:43",
  "file name": "rsd109TheLostClub.mp3",
  "byte size": "31,271,754",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Lost Club",
  "book author": "Arthur Machen",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheLostClubByArthurMachen.pdf",
  "video link": "",
  "podcast description": "The Lost Club by Arthur Machen"
 },
 {
  "episode number": "108",
  "publish date": "2018-02-28 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-108-the-angry-street-a-bad-dream-by-g-k-chesterton/",
  "hh:mm:ss": "0:30:00",
  "file name": "rsd108TheAngryStreet.mp3",
  "byte size": "29,629,002",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Angry Street: A Bad Dream",
  "book author": "G.K. Chesterton",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheAngryStreetABadDreamByG.K.Chesterton.pdf",
  "video link": "",
  "podcast description": "The Angry Street: A Bad Dream by G.K. Chesterton"
 },
 {
  "episode number": "107",
  "publish date": "2018-02-21 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-107-the-man-from-the-atom-by-g-peyton-wertenbaker/",
  "hh:mm:ss": "0:33:49",
  "file name": "rsd107TheManFromTheAtom.mp3",
  "byte size": "33,287,178",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Man From The Atom",
  "book author": "G. Peyton Wertenbaker",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheManFromTheAtomByG.PeytonWertenbaker.pdf",
  "video link": "",
  "podcast description": "The Man From The Atom by G. Peyton Wertenbaker"
 },
 {
  "episode number": "106",
  "publish date": "2018-02-14 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-106-a-year-off-by-h-p-lovecraft/",
  "hh:mm:ss": "0:29:27",
  "file name": "rsd106AYearOff.mp3",
  "byte size": "29,088,270",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "A Year Off",
  "book author": "H.P. Lovecraft",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/can-pdfs/AYearOffByH.P.Lovecraft.pdf",
  "video link": "",
  "podcast description": "A Year Off by H.P. Lovecraft"
 },
 {
  "episode number": "105",
  "publish date": "2018-02-07 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-105-the-haunted-house/",
  "hh:mm:ss": "0:33:05",
  "file name": "rsd105TheHauntedHouse.mp3",
  "byte size": "32,583,882",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Haunted House",
  "book author": "Segundo de Chomón",
  "genre type": "Other",
  "pdf link": "",
  "video link": "https://archive.org/download/NawiedzonyDom1908ReSegundoDeChomon/Nawiedzony%20Dom%20%281908%29%20-%20re%C5%BC%20Segundo%20de%20Chomon.mp4",
  "podcast description": "The Haunted House by Segundo de Chomón"
 },
 {
  "episode number": "104",
  "publish date": "2018-01-31 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-104-the-sphinx-by-edgar-allan-poe/",
  "hh:mm:ss": "0:31:31",
  "file name": "rsd104TheSphinx.mp3",
  "byte size": "31,079,946",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Sphinx",
  "book author": "Edgar Allan Poe",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheSphinxByEdgarAllanPoeArthursLadiesMagazineJan1846.pdf",
  "video link": "",
  "podcast description": "The Sphinx by Edgar Allan Poe"
 },
 {
  "episode number": "103",
  "publish date": "2018-01-24 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-103-note-for-a-time-capsule-by-edward-wellen/",
  "hh:mm:ss": "0:30:33",
  "file name": "rsd103NoteForATimeCapsule.mp3",
  "byte size": "30,153,162",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Note For A Time Capsule",
  "book author": "Edward Wellen",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/NoteForATimeCapsuleByEdwardWellen.pdf",
  "video link": "",
  "podcast description": "Note For A Time Capsule by Edward Wellen"
 },
 {
  "episode number": "102",
  "publish date": "2018-01-17 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-102-the-killers-by-ernest-hemingway/",
  "hh:mm:ss": "0:31:03",
  "file name": "rsd102TheKillers.mp3",
  "byte size": "30,628,362",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Killers",
  "book author": "Ernest Hemingway",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/can-pdfs/TheKillersByErnestHemingwayScribnersMar1927.pdf",
  "video link": "",
  "podcast description": "The Killers by Ernest Hemingway"
 },
 {
  "episode number": "101",
  "publish date": "2018-01-10 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-101-the-beautiful-suit-by-h-g-wells/",
  "hh:mm:ss": "0:31:47",
  "file name": "rsd101TheBeautifulSuit.mp3",
  "byte size": "31,340,298",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Beautiful Suit",
  "book author": "H.G. Wells",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheBeautifulSuitByH.G.Wells.pdf",
  "video link": "",
  "podcast description": "The Beautiful Suit by H.G. Wells"
 },
 {
  "episode number": "100",
  "publish date": "2018-01-03 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-100-the-ghosts-by-lord-dunsany/",
  "hh:mm:ss": "0:28:06",
  "file name": "rsd100TheGhosts.mp3",
  "byte size": "27,810,570",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Ghosts",
  "book author": "Lord Dunsany",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheGhostsByLordDunsany.pdf",
  "video link": "",
  "podcast description": "The Ghosts by Lord Dunsany"
 },
 {
  "episode number": "99",
  "publish date": "2017-12-27 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-099-the-damned-thing-by-ambrose-bierce/",
  "hh:mm:ss": "0:29:55",
  "file name": "rsd099TheDamnedThing.mp3",
  "byte size": "29,552,394",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Damned Thing",
  "book author": "Ambrose Bierce",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheDamnedThingByAmbroseBierceITMOL1898.pdf",
  "video link": "",
  "podcast description": "The Damned Thing by Ambrose Bierce"
 },
 {
  "episode number": "98",
  "publish date": "2017-12-20 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-098-morgue-ship-by-ray-bradbury/",
  "hh:mm:ss": "0:29:45",
  "file name": "rsd098MorgueShip.mp3",
  "byte size": "29,389,386",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Morgue Ship",
  "book author": "Ray Bradbury",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/MorgueShipByRayBradbury.pdf",
  "video link": "",
  "podcast description": "Morgue Ship by Ray Bradbury"
 },
 {
  "episode number": "97",
  "publish date": "2017-12-13 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-097-the-stroke-of-the-sun-by-arthur-c-clarke/",
  "hh:mm:ss": "0:32:36",
  "file name": "rsd097StrokeOfTheSun.mp3",
  "byte size": "32,129,418",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Stroke Of The Sun",
  "book author": "Arthur C. Clarke",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheStrokeOfTheSunByArthurC.Clarke.pdf",
  "video link": "",
  "podcast description": "The Stroke Of The Sun by Arthur C. Clarke"
 },
 {
  "episode number": "96",
  "publish date": "2017-12-06 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-096-moxons-master-by-ambrose-bierce/",
  "hh:mm:ss": "0:33:54",
  "file name": "rsd096MoxonsMaster.mp3",
  "byte size": "33,371,850",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Moxon's Master",
  "book author": "Ambrose Bierce",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/MoxonsMasterByAmbroseBierce.pdf",
  "video link": "",
  "podcast description": "Moxon's Master by Ambrose Bierce"
 },
 {
  "episode number": "95",
  "publish date": "2017-11-29 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-095-crickets-by-richard-matheson/",
  "hh:mm:ss": "0:33:26",
  "file name": "rsd095Crickets.mp3",
  "byte size": "32,921,479",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Crickets",
  "book author": "Richard Matheson",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/CricketsByRichardMatheson.pdf",
  "video link": "",
  "podcast description": "Crickets by Richard Matheson"
 },
 {
  "episode number": "94",
  "publish date": "2017-11-22 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-094-and-all-the-earth-a-grave-by-c-c-mccapp/",
  "hh:mm:ss": "0:29:46",
  "file name": "rsd094AndAllTheEarthAGrave.mp3",
  "byte size": "29,409,546",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "And All The Earth A Grave",
  "book author": "C.C. MacApp",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/And%20All%20The%20Earth%20A%20Grave%20by%20C.C.%20MacApp.pdf",
  "video link": "",
  "podcast description": "And All The Earth A Grave by C.C. MacApp"
 },
 {
  "episode number": "93",
  "publish date": "2017-11-15 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-093-the-glass-of-supreme-moments-by-barry-pain/",
  "hh:mm:ss": "0:31:24",
  "file name": "rsd093TheGlassOfSupremeMoments.mp3",
  "byte size": "30,975,114",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Glass Of Supreme Moments",
  "book author": "Barry Pain",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheGlassOfSupremeMomentsByBarryPain.pdf",
  "video link": "",
  "podcast description": "The Glass Of Supreme Mioments by Barry Pain"
 },
 {
  "episode number": "92",
  "publish date": "2017-11-08 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-092-the-horde-of-the-gibbelins-by-lord-dunsany/",
  "hh:mm:ss": "0:30:37",
  "file name": "rsd092TheHordeOfTheGibbelins.mp3",
  "byte size": "30,227,466",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Hoard Of The Gibbelins",
  "book author": "Lord Dunsany",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheHoardOfTheGibbelinsByLordDunsany.pdf",
  "video link": "",
  "podcast description": "The Hoard Of The Gibbelins by Lord Dunsay"
 },
 {
  "episode number": "91",
  "publish date": "2017-11-01 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-091-the-place-of-pain-by-m-p-shiel/",
  "hh:mm:ss": "0:34:22",
  "file name": "rsd091ThePlaceOfPain.mp3",
  "byte size": "33,806,730",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Place Of Pain",
  "book author": "M.P. Shiel",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/ThePlaceOfPainByM.P.Shiel.pdf",
  "video link": "",
  "podcast description": "The Place Of Pain by M.P. Shiel"
 },
 {
  "episode number": "90",
  "publish date": "2017-10-25 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-090-an-express-of-the-future-by-jules-verne/",
  "hh:mm:ss": "0:29:03",
  "file name": "rsd090AnExpressOfTheFuture.mp3",
  "byte size": "28,714,314",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "An Express Of The Future",
  "book author": "Jules Verne",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/AnExpressOfTheFutureByJulesVerne.pdf",
  "video link": "",
  "podcast description": "An Express Of The Future by Jules Verne"
 },
 {
  "episode number": "89",
  "publish date": "2017-10-18 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-089-the-malice-of-inanimate-objects-by-m-r-james/",
  "hh:mm:ss": "0:31:55",
  "file name": "rsd089TheMalice.mp3",
  "byte size": "31,467,018",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Malice Of Inanimate Objects",
  "book author": "M.R. James",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheMaliceOfInanimateObjectsByM.R.James.pdf",
  "video link": "",
  "podcast description": "The Malice Of Inanimate Objects by M.R. James"
 },
 {
  "episode number": "88",
  "publish date": "2017-10-11 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-088-neutral-tones-by-thomas-hardy/",
  "hh:mm:ss": "0:25:33",
  "file name": "rsd088NeutralTones.mp3",
  "byte size": "25,357,962",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Neutral Tones",
  "book author": "Thomas Hardy",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/NeutralTonesByThomasHardyWessexPoemsAndOtherVerses1899.pdf",
  "video link": "",
  "podcast description": "Neutral Tones by Thomas Hardy"
 },
 {
  "episode number": "87",
  "publish date": "2017-10-04 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-087-seven-day-terror-by-r-a-lafferty/",
  "hh:mm:ss": "0:32:17",
  "file name": "rsd087SevenDayTerror.mp3",
  "byte size": "31,824,714",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Seven-Day Terror",
  "book author": "R.A. Lafferty",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/SevenDayTerrorByR.A.Lafferty.pdf",
  "video link": "",
  "podcast description": "Seven-Day Terror by R.A. Lafferty"
 },
 {
  "episode number": "86",
  "publish date": "2017-09-27 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-086-when-time-turned-by-ethel-watts-mumford/",
  "hh:mm:ss": "0:33:37",
  "file name": "rsd086WhenTimeTurned.mp3",
  "byte size": "33,085,578",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "When Time Turned",
  "book author": "Ethel Watts Mumford",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/WhenTimeTurnedByEthelWattsMumfordTheBlackCatJan1901.pdf",
  "video link": "",
  "podcast description": "When Time Turned by Ethel Watts Mumford"
 },
 {
  "episode number": "85",
  "publish date": "2017-09-20 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-085-the-lifeboat-mutiny-by-robert-sheckley/",
  "hh:mm:ss": "0:31:46",
  "file name": "rsd085TheLifeboatMutiny.mp3",
  "byte size": "31,321,866",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Lifeboat Mutiny",
  "book author": "Robert Sheckley",
  "genre type": "Other",
  "pdf link": "",
  "video link": "http://www.archive.org/download/XMinus1B/xminusone_560911_TheLifeboatMutiny.mp3",
  "podcast description": "The Lifeboat Mutiny by Robert Sheckley"
 },
 {
  "episode number": "84",
  "publish date": "2017-09-13 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-084-the-thing-in-the-forest-by-bernard-capes/",
  "hh:mm:ss": "0:32:02",
  "file name": "rsd084TheThingInTheForest.mp3",
  "byte size": "31,581,642",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Thing In The Forest",
  "book author": "Bernard Capes",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheThingInTheForestByBernardCapes.pdf",
  "video link": "",
  "podcast description": "The Thing In The Forest by Bernard Capes"
 },
 {
  "episode number": "83",
  "publish date": "2017-09-06 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-083-the-bowmen-by-arthur-machen/",
  "hh:mm:ss": "0:35:36",
  "file name": "rsd083TheBowmen.mp3",
  "byte size": "35,001,930",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Bowmen",
  "book author": "Arthur Machen",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheBowmenByArthurMachenWT.pdf",
  "video link": "",
  "podcast description": "The Bowmen by Arthur Machen"
 },
 {
  "episode number": "82",
  "publish date": "2017-08-30 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-082-finis-by-frank-lillie-pollock/",
  "hh:mm:ss": "0:34:09",
  "file name": "rsd082Finis.mp3",
  "byte size": "33,612,618",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Finis",
  "book author": "Frank Lillie Pollock",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/FinisByFrankLilliePollockFantasticNovelsJuly1948.pdf",
  "video link": "",
  "podcast description": "Finis by Frank Lillie Pollock"
 },
 {
  "episode number": "81",
  "publish date": "2017-08-23 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-081-the-dancers-by-margaret-st-clair/",
  "hh:mm:ss": "0:26:54",
  "file name": "rsd081TheDancers.mp3",
  "byte size": "26,651,082",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Dancers",
  "book author": "Margaret St. Clair",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheDancersByMargaretSt.Clair.pdf",
  "video link": "",
  "podcast description": "The Dancers by Margaret St. Clair"
 },
 {
  "episode number": "80",
  "publish date": "2017-08-16 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-080-une-charone-by-charles-baudelaire/",
  "hh:mm:ss": "0:29:53",
  "file name": "rsd080UneCharogne.mp3",
  "byte size": "29,516,106",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Une Charogne",
  "book author": "Charles Baudelaire",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/UneCharogneByCharlesBaudelaireTranslatedByClarkAshtonSmith.pdf",
  "video link": "",
  "podcast description": "Une Charogne by Charles Baudelaire"
 },
 {
  "episode number": "79",
  "publish date": "2017-08-09 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-079-the-star-by-h-g-wells/",
  "hh:mm:ss": "0:30:49",
  "file name": "rsd079TheStar.mp3",
  "byte size": "30,412,362",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Star",
  "book author": "H.G. Wells",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheStarByH.G.Wells.pdf",
  "video link": "",
  "podcast description": "The Star by H.G. Wells"
 },
 {
  "episode number": "78",
  "publish date": "2017-08-02 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-078-the-rejected-sorcerer-by-jorge-luis-borges/",
  "hh:mm:ss": "0:32:13",
  "file name": "rsd078TheRejectedSorcerer.mp3",
  "byte size": "31,756,746",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Rejected Sorcerer",
  "book author": "Jorge Luis Borges",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheRejectedSorcererByJorgeLuisBorges.pdf",
  "video link": "",
  "podcast description": "The Rejected Sorcerer by Jorge Luis Borges"
 },
 {
  "episode number": "77",
  "publish date": "2017-07-26 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-077-one-summer-night-by-ambrose-bierce/",
  "hh:mm:ss": "0:27:08",
  "file name": "rsd077OneSummerNight.mp3",
  "byte size": "26,879,178",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "One Summer Night",
  "book author": "Ambrose Bierce",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/OneSummerNightByAmbroseBierceCTOHCC.pdf",
  "video link": "",
  "podcast description": "One Summer Night by Ambrose Bierce"
 },
 {
  "episode number": "76",
  "publish date": "2017-07-19 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-076-gods-man-by-lynd-ward/",
  "hh:mm:ss": "0:36:49",
  "file name": "rsd076GodsMan.mp3",
  "byte size": "36,178,698",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Gods' Man",
  "book author": "Lynd Ward",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/GodsManANovelInWoodcutsByLyndWard.pdf",
  "video link": "",
  "podcast description": "Gods' Man by Lynd Ward"
 },
 {
  "episode number": "75",
  "publish date": "2017-07-12 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-075-the-other-now-by-murray-leinster/",
  "hh:mm:ss": "0:31:24",
  "file name": "rsd075TheOtherNow.mp3",
  "byte size": "30,979,146",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Other Now",
  "book author": "Murray Leinster",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheOtherNowByMurrayLeinster.pdf",
  "video link": "",
  "podcast description": "The Other Now by Murray Leinster"
 },
 {
  "episode number": "74",
  "publish date": "2017-07-05 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-074-goblin-market-by-christina-rossetti/",
  "hh:mm:ss": "0:32:05",
  "file name": "rsd074GoblinMarket.mp3",
  "byte size": "31,623,114",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Goblin Market",
  "book author": "Christina Rossetti",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/GoblinMarketByChristinaRossetti.pdf",
  "video link": "",
  "podcast description": "Goblin Market by Christina Rossetti"
 },
 {
  "episode number": "73",
  "publish date": "2017-06-28 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-073-a-practical-mans-guide-by-jack-vance/",
  "hh:mm:ss": "0:38:23",
  "file name": "rsd073APracticalMansGuide.mp3",
  "byte size": "37,676,298",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "A Practical Man's Guide",
  "book author": "Jack Vance",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/APracticalMansGuideByJackVance.pdf",
  "video link": "",
  "podcast description": "A Practical Man's Guide by Jack Vance"
 },
 {
  "episode number": "72",
  "publish date": "2017-06-21 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-072-the-wind-by-ray-bradbury",
  "hh:mm:ss": "0:31:16",
  "file name": "rsd072TheWind.mp3",
  "byte size": "30,843,210",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Wind",
  "book author": "Ray Bradbury",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheWindByRayBradbury.pdf",
  "video link": "",
  "podcast description": "The Wind by Ray Bradbury"
 },
 {
  "episode number": "71",
  "publish date": "2017-06-14 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-071-la-chasse-galerie-by-honore-beaugrand/",
  "hh:mm:ss": "0:35:29",
  "file name": "rsd071LaChasseGalerie.mp3",
  "byte size": "34,898,826",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "La Chasse-Galerie",
  "book author": "Honoré Beaugrand",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/LaChasseGalerieByHonoreBeaugrand.pdf",
  "video link": "",
  "podcast description": "La Chasse-Galerie by Honoré Beaugrand"
 },
 {
  "episode number": "70",
  "publish date": "2017-06-07 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-070-miss-brill-by-katherine-mansfield/",
  "hh:mm:ss": "0:34:10",
  "file name": "rsd070MissBrill.mp3",
  "byte size": "33,625,866",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Miss Brill",
  "book author": "Katherine Mansfield",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/MissBrillByKatherineMansfield.pdf",
  "video link": "",
  "podcast description": "Miss Brill by Katherine Mansfield"
 },
 {
  "episode number": "69",
  "publish date": "2017-05-31 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-069-riyas-foundling-by-algis-budrys/",
  "hh:mm:ss": "0:37:02",
  "file name": "rsd069RiyasFoundling.mp3",
  "byte size": "36,379,722",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Riya's Foundling",
  "book author": "Algis Budrys",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/RiyasFoundlingByAlgisBudrys.pdf",
  "video link": "",
  "podcast description": "Riya's Foundling by Algis Budrys"
 },
 {
  "episode number": "68",
  "publish date": "2017-05-24 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-068-cinderella-by-bros-grimm-lucy-crane-translation/",
  "hh:mm:ss": "0:30:53",
  "file name": "rsd068Cinderella.mp3",
  "byte size": "30,479,221",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Cinderella",
  "book author": "Bros. Grimm (Lucy Crane translation)",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/AschenputtelTranslatedByLucyCrane.pdf",
  "video link": "",
  "podcast description": "Cinderella by Bros. Grimm"
 },
 {
  "episode number": "67",
  "publish date": "2017-05-17 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-067-fear-by-achmed-abdullah",
  "hh:mm:ss": "0:30:34",
  "file name": "rsd067Fear.mp3",
  "byte size": "30,180,234",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Fear",
  "book author": "Achmed Abdullah",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/FearByAchmedAbdullah.pdf",
  "video link": "",
  "podcast description": "Fear by Achmed Abdullah"
 },
 {
  "episode number": "66",
  "publish date": "2017-05-10 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-066-spider-woman-by-maria-moravsky/",
  "hh:mm:ss": "0:30:49",
  "file name": "rsd066SpiderWoman.mp3",
  "byte size": "30,418,698",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Spider Woman",
  "book author": "Maria Moravsky",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/SpiderWomanByMariaMoravsky.pdf",
  "video link": "",
  "podcast description": "Spider Woman by Maria Moravsky"
 },
 {
  "episode number": "65",
  "publish date": "2017-05-03 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-065-the-hill-woman-by-frances-elliott/",
  "hh:mm:ss": "0:26:25",
  "file name": "rsd065TheHillWoman.mp3",
  "byte size": "26,193,738",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Hill Woman",
  "book author": "Frances Elliot",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/TheHillWomanByFrancesElliott.pdf",
  "video link": "",
  "podcast description": "The Hill Woman by Frances Elliot"
 },
 {
  "episode number": "64",
  "publish date": "2017-04-26 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-064-jabberwocky-by-lewis-carroll/",
  "hh:mm:ss": "0:31:12",
  "file name": "rsd064Jabberwocky.mp3",
  "byte size": "30,771,786",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Jabberwocky",
  "book author": "Lewis Carroll",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/JabberwockyFromThroughTheLookingGlass1897JohnTennielIllos.pdf",
  "video link": "",
  "podcast description": "Jabberwocky by Lewis Carroll"
 },
 {
  "episode number": "63",
  "publish date": "2017-04-19 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-063-the-hashish-man-by-lord-dunsany/",
  "hh:mm:ss": "0:30:20",
  "file name": "rsd063TheHashishMan.mp3",
  "byte size": "29,944,714",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Hashish Man",
  "book author": "Lord Dunsany",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheHashishManByLordDunsany.pdf",
  "video link": "",
  "podcast description": "The Hashish Man by Lord Dunsany"
 },
 {
  "episode number": "62",
  "publish date": "2017-04-12 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-062-my-last-duchess-by-robert-browning/",
  "hh:mm:ss": "0:31:48",
  "file name": "rsd062MyLastDuchess.mp3",
  "byte size": "31,355,850",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "My Last Duchess",
  "book author": "Robert Browning",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/MyLastDuchessByRobertBrowningDRAMATICLYRICS1898.pdf",
  "video link": "",
  "podcast description": "My Last Duchess by Robert Browning"
 },
 {
  "episode number": "61",
  "publish date": "2017-04-05 00:01",
  "post link": "http://www.sffaudio.com/reading-short-061-platos-dream-by-voltaire",
  "hh:mm:ss": "0:30:15",
  "file name": "rsd061PlatosDream.mp3",
  "byte size": "29,865,738",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Plato's Dream",
  "book author": "Voltaire",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/PlatosDreamByVoltaireTheCompleteRomancesOfVoltaire1927.pdf",
  "video link": "",
  "podcast description": "Plato's Dream by Voltaire"
 },
 {
  "episode number": "60",
  "publish date": "2017-03-29 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-060-two-friends-by-guy-de-maupassant/",
  "hh:mm:ss": "0:31:32",
  "file name": "rsd060TwoFishers.mp3",
  "byte size": "31,260,234",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Two Friends",
  "book author": "Guy de Maupassant",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TwoFishersByGuydDeMaupassant.pdf",
  "video link": "",
  "podcast description": "Two Friends by Guy de Maupassant"
 },
 {
  "episode number": "59",
  "publish date": "2017-03-22 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-059-built-up-logically-by-howard-schoenfeld/",
  "hh:mm:ss": "0:32:30",
  "file name": "rsd059BuiltUpLogically.mp3",
  "byte size": "32,021,706",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Built Up Logically",
  "book author": "Howard Schoenfeld",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheUniversalPanaceaByHowardSchoenfeld.pdf",
  "video link": "",
  "podcast description": "The Universal Panacea by Howard Schoenfeld"
 },
 {
  "episode number": "58",
  "publish date": "2017-03-15 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-058-i-am-by-john-clare",
  "hh:mm:ss": "0:32:34",
  "file name": "rsd058IAm.mp3",
  "byte size": "32,093,130",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "I Am",
  "book author": "John Clare",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/IAmByJohnClare.pdf",
  "video link": "",
  "podcast description": "I Am by John Clare"
 },
 {
  "episode number": "57",
  "publish date": "2017-03-08 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-057-stateroom-six-by-william-albert-lewis",
  "hh:mm:ss": "0:33:59",
  "file name": "rsd057StateroomSix.mp3",
  "byte size": "33,449,610",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Stateroom Six",
  "book author": "Willam Albert Lewis",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/StateroomSixByWillamAlbertLewis.pdf",
  "video link": "",
  "podcast description": "Stateroom Six by William Albert Lewis"
 },
 {
  "episode number": "56",
  "publish date": "2017-03-01 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-056-dulce-et-decorum-est-by-wilfred-owen",
  "hh:mm:ss": "0:33:40",
  "file name": "rsd056DolceEtDecorumEst.mp3",
  "byte size": "33,147,210",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Dolce Et Decorum Est",
  "book author": "Wilfred Owen",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/DulceEtDecorumEstByWilfredOwen.pdf",
  "video link": "",
  "podcast description": "Dolce Et Decorum Est by Wilfred Owen"
 },
 {
  "episode number": "55",
  "publish date": "2017-02-22 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-055-desirees-baby-by-kate-chopin",
  "hh:mm:ss": "0:38:54",
  "file name": "rsd055DesireesBaby.mp3",
  "byte size": "38,176,842",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Désirée’s Baby",
  "book author": "Kate Chopin",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/DesireesBabyByKateChopinBayouFolk.pdf",
  "video link": "",
  "podcast description": "Désirée's Baby by Kate Chopin"
 },
 {
  "episode number": "54",
  "publish date": "2017-02-15 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-054-hesperia-by-h-p-lovecraft/",
  "hh:mm:ss": "0:30:37",
  "file name": "rsd054Hesperia.mp3",
  "byte size": "30,225,738",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Hesperia",
  "book author": "H.P. Lovecraft",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/HesperiaByH.P.Lovecraft.pdf",
  "video link": "",
  "podcast description": "Hesperia by H.P. Lovecraft"
 },
 {
  "episode number": "53",
  "publish date": "2017-02-08 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-053-the-lake-by-edgar-allan-poe/",
  "hh:mm:ss": "0:30:42",
  "file name": "rsd053TheLake.mp3",
  "byte size": "30,306,378",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Lake",
  "book author": "Edgar Allan Poe",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/TheLakeByEdgarAllanPoeTamarlaneAndOtherPoems1827.pdf",
  "video link": "",
  "podcast description": "The Lake by Edgar Allan Poe"
 },
 {
  "episode number": "52",
  "publish date": "2017-02-01 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-052-the-eyes-have-it-by-philip-k-dick",
  "hh:mm:ss": "0:31:16",
  "file name": "rsd052TheEyesHaveIt.mp3",
  "byte size": "30,836,874",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Eyes Have It",
  "book author": "Philip K. Dick",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheEyesHaveItByPhilipK.Dick.pdf",
  "video link": "",
  "podcast description": "The Eyes Have It by Philip K. Dick"
 },
 {
  "episode number": "51",
  "publish date": "2017-01-25 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-051-anecdote-of-the-jar-by-wallace-stevens/",
  "hh:mm:ss": "0:30:52",
  "file name": "rsd051AnecdoteOfTheJar.mp3",
  "byte size": "30,452,106",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Anecdote Of The Jar",
  "book author": "Wallace Stevens",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/AnecdoteOfTheJarByWallaceStevensPoetryMagazineOctober1919.pdf",
  "video link": "",
  "podcast description": "Anecodte Of The Jar by Wallace Stevens"
 },
 {
  "episode number": "50",
  "publish date": "2017-01-18 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-050-the-uncharted-isle-by-clark-ashton-smith",
  "hh:mm:ss": "0:31:50",
  "file name": "rsd050TheUnchartedIsle.mp3",
  "byte size": "31,392,714",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Uncharted Isle",
  "book author": "Clark Ashton Smith",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheUnchartedIsleByClarkAshtonSmith.pdf",
  "video link": "",
  "podcast description": "The Uncharted Isle by Clark Ashton Smith"
 },
 {
  "episode number": "49",
  "publish date": "2017-01-11 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-049-the-eater-of-souls-by-henry-kuttner",
  "hh:mm:ss": "0:33:22",
  "file name": "rsd049TheEaterOfSouls.mp3",
  "byte size": "32,866,122",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Eater Of Souls",
  "book author": "Henry Kuttner",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheEaterOfSoulsByHenryKuttner.pdf",
  "video link": "",
  "podcast description": "The Eater Of Souls by Henry Kuttner"
 },
 {
  "episode number": "48",
  "publish date": "2017-01-04 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-048-the-great-train-robbery",
  "hh:mm:ss": "0:28:44",
  "file name": "rsd048TheGreatTrainRobbery.mp3",
  "byte size": "28,413,642",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Great Train Robbery",
  "book author": "Edwin S. Porter",
  "genre type": "Other",
  "pdf link": "",
  "video link": "https://www.youtube.com/watch?v=8oTdPklBE0Y",
  "podcast description": "The Great Train Robbery by Edwin S. Porter"
 },
 {
  "episode number": "47",
  "publish date": "2016-12-28 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-047-but-who-can-replace-a-man-by-brian-aldiss",
  "hh:mm:ss": "0:32:41",
  "file name": "rsd047ButWhoCanReplaceAMan.mp3",
  "byte size": "32,198,538",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "But Who Can Replace A Man",
  "book author": "Brian Aldiss",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/ButWhoCanReplaceAManByBrianW.Aldiss.pdf",
  "video link": "",
  "podcast description": "But Who Can Replace A Man by Brian Aldiss"
 },
 {
  "episode number": "46",
  "publish date": "2016-12-21 10:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-046-the-voices-by-edward-wellen",
  "hh:mm:ss": "0:32:08",
  "file name": "rsd046TheVoices.mp3",
  "byte size": "31,676,682",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Voices",
  "book author": "Edward Wellen",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheVoicesByEdwardWellen.pdf",
  "video link": "",
  "podcast description": "The Voices by Edward Wellen"
 },
 {
  "episode number": "45",
  "publish date": "2016-12-14 10:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-045-rescued-by-rover",
  "hh:mm:ss": "0:32:54",
  "file name": "rsd045RescuedByRover.mp3",
  "byte size": "32,401,290",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Rescued By Rover",
  "book author": "Cecil Milton Hepworth",
  "genre type": "Other",
  "pdf link": "",
  "video link": "https://www.youtube.com/watch?v=LlhNxHfyWTU",
  "podcast description": "Rescued By Rover by Cecil Milton Hepworth"
 },
 {
  "episode number": "44",
  "publish date": "2016-12-06 17:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-044-the-mansion-of-forgetfulness-by-don-mark-lemon",
  "hh:mm:ss": "0:30:51",
  "file name": "rsd044TheMansionOfForgetfulness.mp3",
  "byte size": "30,439,434",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Mansion Of Forgetfulness",
  "book author": "Don Mark Lemon",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheMansionOfForgetfulnessByDonMarkLemon.pdf",
  "video link": "",
  "podcast description": "The Mansion Of Forgetfulness by Don Mark Lemon"
 },
 {
  "episode number": "43",
  "publish date": "2016-11-30 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-043-the-tree-by-h-p-lovecraft",
  "hh:mm:ss": "0:34:40",
  "file name": "rsd043TheTree.mp3",
  "byte size": "34,115,466",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Tree",
  "book author": "H.P. Lovecraft",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheTreeByH.P.Lovecraft.pdf",
  "video link": "",
  "podcast description": "The Tree by H.P. Lovecraft"
 },
 {
  "episode number": "42",
  "publish date": "2016-11-23 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-042-the-oval-portrait-by-edgar-allan-poe",
  "hh:mm:ss": "0:34:07",
  "file name": "rsd042TheOvalPortrait.mp3",
  "byte size": "33,578,634",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Oval Portrait",
  "book author": "Edgar Allan Poe",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheOvalPortraitByEdgarAllanPoeb.pdf",
  "video link": "",
  "podcast description": "The Oval Portrait by Edgar Allan Poe"
 },
 {
  "episode number": "41",
  "publish date": "2016-11-16 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-041-the-purple-pileus-by-h-g-wells",
  "hh:mm:ss": "0:32:46",
  "file name": "rsd041ThePurplePileus.mp3",
  "byte size": "32,283,210",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Purple Pileus",
  "book author": "H.G. Wells",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/ThePuplePileusByH.G.WellsMethuen1897.pdf",
  "video link": "",
  "podcast description": "The Purple Pileus by H.G. Wells"
 },
 {
  "episode number": "40",
  "publish date": "2016-11-09 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-040-the-night-wire-by-h-f-arnold",
  "hh:mm:ss": "0:31:48",
  "file name": "rsd040TheNightWire.mp3",
  "byte size": "31,359,882",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Night Wire",
  "book author": "H.F. Arnold",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheNightWireByH.F.ArnoldWTJan1933.pdf",
  "video link": "",
  "podcast description": "The Night Wire by H.F. Arnold"
 },
 {
  "episode number": "39",
  "publish date": "2016-11-02 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-039-the-wisdom-of-the-trail-by-jack-london",
  "hh:mm:ss": "0:27:12",
  "file name": "rsd039TheWisdomOfTheTrail.mp3",
  "byte size": "26,941,386",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Wisdom of the Trail",
  "book author": "Jack London",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheWisdomOfTheTrailByJackLondonOVERLANDMONTHLY.pdf",
  "video link": "",
  "podcast description": "The Wisdom of the Trail by Jack London"
 },
 {
  "episode number": "38",
  "publish date": "2016-10-26 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-038-the-highwayman-by-lord-dunsany",
  "hh:mm:ss": "0:27:09",
  "file name": "rsd038TheHighwayman.mp3",
  "byte size": "26,885,514",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Highwayman",
  "book author": "Lord Dunsany",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheHighwaymanByLordDunsany.pdf",
  "video link": "",
  "podcast description": "The Highwayman by Lord Dunsany"
 },
 {
  "episode number": "37",
  "publish date": "2016-10-19 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-037-the-hemp-by-stephen-vincent-benet",
  "hh:mm:ss": "0:32:39",
  "file name": "rsd037TheHemp.mp3",
  "byte size": "32,177,226",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Hemp",
  "book author": "Stephen Vincent Benét",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/TheHempByStephenVincentBenet.pdf",
  "video link": "",
  "podcast description": "The Hemp by Stephen Vincent Benét"
 },
 {
  "episode number": "36",
  "publish date": "2016-10-12 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-036-the-mark-of-the-beast-by-rudyard-kipling",
  "hh:mm:ss": "0:41:56",
  "file name": "rsd036TheMarkOfTheBeast.mp3",
  "byte size": "41,085,066",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Mark of the Beast",
  "book author": "Rudyard Kipling",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheMarkOfTheBeastByRudyardKipling.pdf",
  "video link": "",
  "podcast description": "The Mark of the Beast by Rudyard Kipling"
 },
 {
  "episode number": "35",
  "publish date": "2016-10-06 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-035-the-painter-of-dead-women-by-edna-worthley-underwood",
  "hh:mm:ss": "0:39:44",
  "file name": "rsd035ThePainterOfDeadWomen.mp3",
  "byte size": "38,968,842",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Painter of Dead Women",
  "book author": "Edna Worthley Underwood",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/ThePainterOfDeadWomenByEdnaWorthleyUnderwoodTheSmartSetJan1910.pdf",
  "video link": "",
  "podcast description": "Painter of Dead Women by Edna Worthley Underwood"
 },
 {
  "episode number": "34",
  "publish date": "2016-09-28 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-034-the-cremation-of-sam-mcgee-by-robert-service",
  "hh:mm:ss": "0:28:51",
  "file name": "rsd034TheCremationOfSamMcGee.mp3",
  "byte size": "28,519,788",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Cremation of Sam McGee",
  "book author": "Robert W. Service",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/TheCremationOfSamMcGeeByRobertW.Service.pdf",
  "video link": "",
  "podcast description": "The Cremation of Sam McGee by Robert W. Service"
 },
 {
  "episode number": "33",
  "publish date": "2016-09-21 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-033-the-island-of-the-fay-by-edgar-allan-poe",
  "hh:mm:ss": "0:32:57",
  "file name": "rsd033TheIslandOfTheFay.mp3",
  "byte size": "32,462,346",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Island of the Fay",
  "book author": "Edgar Allan Poe",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheIslandOfTheFayByEdgarAllanPoeGrahamsMagazineJune1841.pdf",
  "video link": "",
  "podcast description": "The Island of the Fay by Edgar Allan Poe"
 },
 {
  "episode number": "32",
  "publish date": "2016-09-13 22:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-032-a-modest-proposal-by-jonathan-swift",
  "hh:mm:ss": "0:36:24",
  "file name": "rsd032AModestProposal.mp3",
  "byte size": "35,772,618",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "A Modest Proposal",
  "book author": "Jonathan Swift",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/AModestProposalByJonathanSwift.pdf",
  "video link": "",
  "podcast description": "A Modest Proposal by Jonathan Swift"
 },
 {
  "episode number": "31",
  "publish date": "2016-09-07 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-31-the-black-cat-by-edgar-allan-poe/",
  "hh:mm:ss": "0:30:12",
  "file name": "rsd031TheBlackCat.mp3",
  "byte size": "29,813,322",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Black Cat",
  "book author": "Edgar Allan Poe",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheBlackCatByEdgarAllanPoeCWoEAPVol5.pdf",
  "video link": "",
  "podcast description": "The Black Cat by Edgar Allan Poe"
 },
 {
  "episode number": "30",
  "publish date": "2016-08-31 00:01",
  "post link": "http://www.sffaudio.com/reading-short-deep-30-the-interlopers-by-saki/",
  "hh:mm:ss": "0:29:20",
  "file name": "rsd030TheInterlopers.mp3",
  "byte size": "28,981,845",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Interlopers",
  "book author": "Saki",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheInterlopersBySaki.pdf",
  "video link": "",
  "podcast description": "The Interlopers by Saki"
 },
 {
  "episode number": "29",
  "publish date": "2016-08-24 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-029-an-inhabitant-of-carcosa-by-ambrose-bierce",
  "hh:mm:ss": "0:34:50",
  "file name": "rsd029AnInhabitantOfCarcosa.mp3",
  "byte size": "34,265,802",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "An Inhabitant Of Carcosa",
  "book author": "Ambrose Bierce",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/AnInhabitantOfCarcosaByAmbroseBierce.pdf",
  "video link": "",
  "podcast description": "An Inhabitant Of Carcosa by Ambrose Bierce"
 },
 {
  "episode number": "28",
  "publish date": "2016-08-17 00:01",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-028-the-storyteller-by-saki/",
  "hh:mm:ss": "0:32:46",
  "file name": "rsd028TheStoryteller.mp3",
  "byte size": "32,283,210",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Story-Teller",
  "book author": "Saki",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheStory-TellerBySaki.pdf",
  "video link": "",
  "podcast description": "The Story Teller by Saki"
 },
 {
  "episode number": "27",
  "publish date": "2016-08-09 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-027-gertie-the-dinosaur/",
  "hh:mm:ss": "0:29:56",
  "file name": "rsd027GertieTheDinosaur.mp3",
  "byte size": "29,561,034",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Gertie The Dinosaur",
  "book author": "Winsor McCay",
  "genre type": "Other",
  "pdf link": "",
  "video link": "https://archive.org/download/Gertie/GertietheDinosaur_512kb.mp4",
  "podcast description": "Gertie The Dinosaur by Winsor McCay"
 },
 {
  "episode number": "26",
  "publish date": "2016-08-02 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-026-a-century-hence-by-w-m-paxton/",
  "hh:mm:ss": "0:32:40",
  "file name": "rsd026ACenturyHence.mp3",
  "byte size": "32,191,050",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "A Century Hence",
  "book author": "W.M. Paxton",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/ACenturyHenceByW.M.Paxton.pdf",
  "video link": "",
  "podcast description": "A Century Hence by W.M. Paxton"
 },
 {
  "episode number": "25",
  "publish date": "2016-07-27 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-025-dr-heideggers-experiment-by-nathaniel-hawthorne/",
  "hh:mm:ss": "0:29:34",
  "file name": "rsd025DrHeideggersExperiment.mp3",
  "byte size": "29,210,250",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Dr. Heidegger's Experiment",
  "book author": "Nathaniel Hawthorne",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/Dr.HeideggersExperimentByNathanielHawthorneTwiceToldTales1837.pdf",
  "video link": "",
  "podcast description": "Dr. Heidegger's Experiment by Nathaniel Hawthorne"
 },
 {
  "episode number": "24",
  "publish date": "2016-07-20 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-024-living-space-by-isaac-asimov",
  "hh:mm:ss": "0:33:31",
  "file name": "rsd024LivingSpace.mp3",
  "byte size": "33,002,058",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Living Space",
  "book author": "Isaac Asimov",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/LivingSpaceByIsaacAsimov.pdf",
  "video link": "",
  "podcast description": "Living Space by Isaac Asimov"
 },
 {
  "episode number": "23",
  "publish date": "2016-07-13 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-023-elys-automatic-housemaid-by-elizabeth-w-bellamy/",
  "hh:mm:ss": "0:30:48",
  "file name": "rsd023ElysAutomaticHousemaid.mp3",
  "byte size": "30,401,994",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Ely's Automatic Housemaid",
  "book author": "Elizabeth W. Bellamy",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/ElysAutomaticHousemaidByElizabethW.Bellamy.pdf",
  "video link": "",
  "podcast description": "Ely's Automatic Housemaid by Elizabeth W. Bellamy"
 },
 {
  "episode number": "22",
  "publish date": "2016-07-06 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-022-hymn-to-beauty-by-charles-baudelaire/",
  "hh:mm:ss": "0:57:00",
  "file name": "rsd022HymnToBeauty.mp3",
  "byte size": "40,141,578",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Hymn to Beauty",
  "book author": "Charles Baudelaire",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/HymnToBeautyByCharlesP.Baudelaire.pdf",
  "video link": "",
  "podcast description": "Hymn to Beauty Charles Baudelaire, translation by Clark Ashton Smith"
 },
 {
  "episode number": "21",
  "publish date": "2016-06-29 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-021-moon-face-by-jack-london/",
  "hh:mm:ss": "0:37:07",
  "file name": "rsd021MoonFace.mp3",
  "byte size": "29,744,778",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Moon-Face",
  "book author": "Jack London",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/Moon-FaceByJackLondon.pdf",
  "video link": "",
  "podcast description": "Moon-Face by Jack London"
 },
 {
  "episode number": "20",
  "publish date": "2016-06-22 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-020-strange-exodus-by-robert-abernathy/",
  "hh:mm:ss": "0:32:25",
  "file name": "rsd020StrangeExodus.mp3",
  "byte size": "31,363,872",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Strange Exodus",
  "book author": "Robert Abernathy",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/StrangeExodusByRobertAbernathy.pdf",
  "video link": "",
  "podcast description": "Strange Exodus by Robert Abernathy"
 },
 {
  "episode number": "19",
  "publish date": "2016-06-15 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-019-the-false-rhyme-by-mary-shelley/",
  "hh:mm:ss": "0:33:02",
  "file name": "rsd019TheFalseRhyme.mp3",
  "byte size": "31,962,912",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The False Rhyme",
  "book author": "Mary Shelley",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheFalseRhymeByMaryShelley.pdf",
  "video link": "",
  "podcast description": "The False Rhyme by Mary Shelley"
 },
 {
  "episode number": "18",
  "publish date": "2016-06-08 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-018-a-pail-of-air-by-fritz-leiber/",
  "hh:mm:ss": "0:39:19",
  "file name": "rsd018APailOfAir.mp3",
  "byte size": "32,226,144",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "A Pail of Air",
  "book author": "Fritz Leiber",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/APailOfAirByFritzLeiber.pdf",
  "video link": "",
  "podcast description": "A Pail of Air by Fritz Leiber"
 },
 {
  "episode number": "17",
  "publish date": "2016-06-01 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-017-the-wolf-by-guy-de-maupassant/",
  "hh:mm:ss": "0:30:30",
  "file name": "rsd017TheWolf.mp3",
  "byte size": "29,531,040",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Wolf",
  "book author": "Guy de Maupassant",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheWolfByGuyDeMaupassant.pdf",
  "video link": "",
  "podcast description": "The Wolf by Guy de Maupassant"
 },
 {
  "episode number": "16",
  "publish date": "2016-05-25 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-016-the-house-by-fredric-brown/",
  "hh:mm:ss": "0:29:53",
  "file name": "rsd016TheHouse.mp3",
  "byte size": "28,930,848",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The House",
  "book author": "Fredric Brown",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheHouseByFredricBrown.pdf",
  "video link": "",
  "podcast description": "The House by Fredric Brown"
 },
 {
  "episode number": "15",
  "publish date": "2016-05-18 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-015-the-mirrors-of-tuzun-thune-by-robert-e-howard/",
  "hh:mm:ss": "0:35:13",
  "file name": "rsd015TheMirrorsOfTuzunThune.mp3",
  "byte size": "34,059,552",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Mirrors of Tuzun Thune",
  "book author": "Robert E. Howard",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheMirrorsOfTuzunThuneByRobertE.HowardWT.pdf",
  "video link": "",
  "podcast description": "The Mirrors of Tuzun Thune by Robert E. Howard"
 },
 {
  "episode number": "14",
  "publish date": "2016-05-11 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-014-the-library-of-babel-by-jorge-luis-borges/",
  "hh:mm:ss": "0:50:59",
  "file name": "rsd014TheLibraryOfBabel.mp3",
  "byte size": "49,193,451",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Library of Babel",
  "book author": "Jorge Luis Borges",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheLibraryOfBabelByJorgeLuisBorges.pdf",
  "video link": "",
  "podcast description": "The Library of Babel by Jorge Luis Borges"
 },
 {
  "episode number": "13",
  "publish date": "2016-05-04 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-013-the-dog-and-the-horse-by-voltaire/",
  "hh:mm:ss": "0:31:22",
  "file name": "rsd013TheDogAndTheHorse.mp3",
  "byte size": "30,352,416",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Dog and the Horse",
  "book author": "Voltaire",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheDogAndThe%20HorseByVoltaire.pdf",
  "video link": "",
  "podcast description": "The Dog and the Horse by Voltaire"
 },
 {
  "episode number": "12",
  "publish date": "2016-04-27 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-012-all-cats-are-gray-by-andre-norton",
  "hh:mm:ss": "0:32:31",
  "file name": "rsd012AllCatsAreGray.mp3",
  "byte size": "31,455,456",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "All Cats Are Grey",
  "book author": "Andre Norton",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/AllCatsAreGrayByAndreNorton.pdf",
  "video link": "",
  "podcast description": "All Cats Are Grey by Andre Norton"
 },
 {
  "episode number": "11",
  "publish date": "2016-04-20 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-011-the-roller-coaster-by-alfred-bester",
  "hh:mm:ss": "0:37:15",
  "file name": "rsd011TheRollercoaster.mp3",
  "byte size": "35,998,944",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Rollercoaster",
  "book author": "Alfred Bester",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheRollerCoasterByAlfredBester.pdf",
  "video link": "",
  "podcast description": "The Rollercoaster by Alfred Bester"
 },
 {
  "episode number": "10",
  "publish date": "2016-04-13 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-010-la-belle-dame-sans-merci-by-john-keats",
  "hh:mm:ss": "0:30:24",
  "file name": "rsd010LaBelleDameSansMercy.mp3",
  "byte size": "29,438,304",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "La Belle Dame Sans Mercy",
  "book author": "John Keats",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/LaBelleDameSansMercyByJohnKeatsINDICATORMay101820.pdf",
  "video link": "",
  "podcast description": "La Belle Dame sans Mercy by John Keats"
 },
 {
  "episode number": "9",
  "publish date": "2016-04-06 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-009-the-nine-billion-names-of-god-by-sir-arthur-c-clarke",
  "hh:mm:ss": "0:36:13",
  "file name": "rsd009NineBillion.mp3",
  "byte size": "35,007,329",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Nine Billion Names Of God",
  "book author": "Arthur C. Clarke",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheNineBillionNamesOfGodByArthurC.Clarke.pdf",
  "video link": "",
  "podcast description": "Nine Billion by Arthur C. Clarke"
 },
 {
  "episode number": "8",
  "publish date": "2016-3-30 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-008-dream-land-by-edgar-allan-poe",
  "hh:mm:ss": "0:34:01",
  "file name": "rsd008Dreamland.mp3",
  "byte size": "32,909,174",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Dream-Land",
  "book author": "Edgar Allan Poe",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/DreamLandByEdgarAllanPoeGrahamsLadysAndGentlemansMagazineJune1844.pdf",
  "video link": "",
  "podcast description": "Dreamland by Edgar Allan Poe"
 },
 {
  "episode number": "7",
  "publish date": "2016-3-23 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-007-beyond-lies-the-wub-by-philip-k-dick",
  "hh:mm:ss": "0:33:34",
  "file name": "rsd007BeyondLiesTheWub.mp3",
  "byte size": "32,473,243",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Beyond Lies The Wub",
  "book author": "Philip K. Dick",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/BeyondLiesTheWubByPhilipK.Dick.pdf",
  "video link": "",
  "podcast description": "Beyond Lies the Wub by Philip K. Dick"
 },
 {
  "episode number": "6",
  "publish date": "2016-3-16 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-006-friend-island-by-francis-stevens",
  "hh:mm:ss": "0:40:10",
  "file name": "rsd006FriendIsland.mp3",
  "byte size": "38,811,176",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Friend Island",
  "book author": "Francis Stevens",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/FriendIslandByFrancisStevens.pdf",
  "video link": "",
  "podcast description": "Friend Island by Francis Stevens"
 },
 {
  "episode number": "5",
  "publish date": "2016-3-9 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-005-the-ancient-track-by-h-p-lovecraft",
  "hh:mm:ss": "0:32:53",
  "file name": "rsd005TheAncientTrack.mp3",
  "byte size": "31,810,320",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Ancient Track",
  "book author": "H.P. Lovecraft",
  "genre type": "Poem",
  "pdf link": "http://www.sffaudio.com/podcasts/TheAncientTrackByH.P.LovecraftWEIRDTALESMarch1930.pdf",
  "video link": "",
  "podcast description": "The Ancient Track by H.P. Lovecraft"
 },
 {
  "episode number": "4",
  "publish date": "2016-3-2 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-004-the-words-of-guru-by-c-m-kornbluth",
  "hh:mm:ss": "0:35:47",
  "file name": "rsd004TheWordsOfGuru.mp3",
  "byte size": "34,598,565",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Words of Guru",
  "book author": "C.M. Kornbluth",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheWordsOfGuruByC.M.KornbluthAFR5.pdf",
  "video link": "",
  "podcast description": "The Words of Guru by C.M. Kornbluth"
 },
 {
  "episode number": "3",
  "publish date": "2016-2-24 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-003-the-flowering-of-the-strange-orchid-by-h-g-wells",
  "hh:mm:ss": "0:26:34",
  "file name": "rsd003StrangeOrchid.mp3",
  "byte size": "25,753,056",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "The Flowering Of The Strange Orchid",
  "book author": "H.G. Wells",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/TheFloweringOfTheStrangeOrchidByH.G.WellsPEARSONS.pdf",
  "video link": "",
  "podcast description": "The Flowering Of The Strange Orchid by H.G. Wells"
 },
 {
  "episode number": "2",
  "publish date": "2016-2-17 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-002-rapunzel-by-the-brothers-grimm",
  "hh:mm:ss": "0:30:19",
  "file name": "rsd002Rapunzel.mp3",
  "byte size": "29,352,408",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Rapunzel",
  "book author": "The Brothers Grimm",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/RapunzelByBrosGrimm.pdf",
  "video link": "",
  "podcast description": "Rapunzel by The Brothers Grimm"
 },
 {
  "episode number": "1",
  "publish date": "2016-2-10 23:00",
  "post link": "http://www.sffaudio.com/reading-short-and-deep-001-zero-hour-by-ray-bradbury",
  "hh:mm:ss": "0:34:05",
  "file name": "rsd001ZeroHour.mp3",
  "byte size": "32,972,064",
  "podcast participants": "Eric S. Rabkin and Jesse Willis",
  "book title": "Zero Hour",
  "book author": "Ray Bradbury",
  "genre type": "Story",
  "pdf link": "http://www.sffaudio.com/podcasts/ZeroHourByRayBradbury.pdf",
  "video link": "",
  "podcast description": "Zero Hour by Ray Bradbury"
 }
] ; 

module.exports = mock_data_return; 