const pdf_pkd = [

{"episode number":"4909","publish date":"2018-07-18 15","book title":"Thunderbolt!",
"book author":"Robert S. Johnson with Martin Caidin","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Robert_S._Johnson",
"pdf link 1":"ThunderboltByRobertS.JohnsonWithMartinCaidin.pdf","pdf page count 1":"234","pdf country 1":"","pdf info 1":"Ballantine Books, 1958","pdf link 2":"",
"pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"",
"pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"712","publish date":"2016-02-10 8","book title":"Adjustment Team","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Adjustment_Team","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"AdjustmentTeamByPhilipK.Dick.pdf","pdf page count 1":"21","pdf country 1":"","pdf info 1":"Orbit, No. 4, September-October 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"711","publish date":"2016-02-10 8","book title":"Beyond The Door","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"BeyondTheDoorByPhilipK.Dick.pdf","pdf page count 1":"7","pdf country 1":"","pdf info 1":"Fantastic Universe, January 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"710","publish date":"2016-02-10 8","book title":"Beyond Lies The Wub","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Beyond_Lies_the_Wub","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"BeyondLiesTheWubByPhilipK.Dick.pdf","pdf page count 1":"6","pdf country 1":"","pdf info 1":"Planet Stories, July 1952","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"709","publish date":"2016-02-10 8","book title":"Breakfast At Twilight","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Breakfast_at_Twilight","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"BreakfastAtTwilightByPhilipK.Dick.pdf","pdf page count 1":"17","pdf country 1":"","pdf info 1":"Amazing Stories, July 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"708","publish date":"2016-02-10 8","book title":"The Crawlers","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Crawlers","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheCrawlersByPhilipK.Dick.pdf","pdf page count 1":"10","pdf country 1":"","pdf info 1":"Imagination, July 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"707","publish date":"2016-02-10 8","book title":"The Crystal Crypt","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Crystal_Crypt","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheCrystalCryptByPhilipK.Dick.pdf","pdf page count 1":"13","pdf country 1":"","pdf info 1":"Planet Stories, January 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"706","publish date":"2016-02-10 8","book title":"The Defenders","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Defenders_%28short_story%29","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheDefendersByPhilipK.Dick.pdf","pdf page count 1":"26","pdf country 1":"","pdf info 1":"Galaxy, January 1953","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"705","publish date":"2016-02-10 8","book title":"Exhibit Piece","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Exhibit_Piece","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"ExhibitPieceByPhilipK.Dick.pdf","pdf page count 1":"14","pdf country 1":"","pdf info 1":"If: Worlds Of Science Fiction, August 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"704","publish date":"2016-02-10 8","book title":"The Eyes Have It","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheEyesHaveItByPhilipK.Dick.pdf","pdf page count 1":"5","pdf country 1":"","pdf info 1":"Science Fiction Stories, 1, 1953","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"703","publish date":"2016-02-10 8","book title":"Foster, You're Dead!","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Foster,_You%27re_Dead!","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"FosterYoureDeadByPhilipK.DickSSF3.pdf","pdf page count 1":"22","pdf country 1":"","pdf info 1":"Star Science Fiction, No. 3, 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"702","publish date":"2016-02-10 8","book title":"The Golden Man","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Golden_Man","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheGoldenManByPhilipK.Dick.pdf","pdf page count 1":"26","pdf country 1":"","pdf info 1":"If: Worlds Of Science Fiction, April 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"701","publish date":"2016-02-10 8","book title":"The Gun","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Gun_%28short_story%29","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheGunByPhilipK.Dick.pdf","pdf page count 1":"9","pdf country 1":"","pdf info 1":"Planet Stories, September 1952","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"700","publish date":"2016-02-10 8","book title":"The Hanging Stranger","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheHangingStrangerByPhilipK.Dick.pdf","pdf page count 1":"16","pdf country 1":"","pdf info 1":"Science Fiction Adventures, December 1953","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"699","publish date":"2016-02-10 8","book title":"Human Is","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Human_Is","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"HumanIsByPhilipK.Dick.pdf","pdf page count 1":"9","pdf country 1":"","pdf info 1":"Startling Stories, Winter 1955","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"698","publish date":"2016-02-10 8","book title":"James P. Crow","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"JamesP.CrowByPhilipK.Dick.pdf","pdf page count 1":"12","pdf country 1":"","pdf info 1":"Planet Stories, May 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"697","publish date":"2016-02-10 8","book title":"The Last Of The Masters","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Last_of_the_Masters","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheLastOfTheMastersByPhilipK.Dick.pdf","pdf page count 1":"28","pdf country 1":"","pdf info 1":"Orbit, No. 5, November-December 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"696","publish date":"2016-02-10 8","book title":"Meddler","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Meddler_%28short_story%29","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"MeddlerByPhilipK.Dick.pdf","pdf page count 1":"13","pdf country 1":"","pdf info 1":"Future Science Fiction, October 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"695","publish date":"2016-02-10 8","book title":"Piper In The Woods","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Piper_in_the_Woods","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"PiperInTheWoodsByPhilipK.Dick.pdf","pdf page count 1":"20","pdf country 1":"","pdf info 1":"Imagination, February 1953","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"694","publish date":"2016-02-10 8","book title":"Progeny","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"ProgenyByPhilipK.Dick.pdf","pdf page count 1":"15","pdf country 1":"","pdf info 1":"If: Worlds Of Science Fiction, November 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"693","publish date":"2016-02-10 8","book title":"Prominent Author","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"ProminentAuthorByPhilipK.Dick.pdf","pdf page count 1":"16","pdf country 1":"","pdf info 1":"If: Worlds Of Science Fiction, May 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"692","publish date":"2016-02-10 8","book title":"Sales Pitch","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Sales_Pitch_%28short_story%29","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"SalesPitchByPhilipK.Dick.pdf","pdf page count 1":"16","pdf country 1":"","pdf info 1":"Future Science Fiction, June 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"691","publish date":"2016-02-10 8","book title":"Second Variety","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Second_Variety","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"SecondVarietyByPhilipK.Dick.pdf","pdf page count 1":"44","pdf country 1":"","pdf info 1":"Space Science Fiction, May 1953","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"690","publish date":"2016-02-10 8","book title":"Shell Game","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Shell_Game_%28short_story%29","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"ShellGameByPhilipK.Dick.pdf","pdf page count 1":"16","pdf country 1":"","pdf info 1":"Galaxy, September 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"689","publish date":"2016-02-10 8","book title":"The Skull","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Skull_%28short_story%29","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheSkullByPhilipK.Dick.pdf","pdf page count 1":"18","pdf country 1":"","pdf info 1":"If: Worlds Of Science Fiction, September 1952","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"688","publish date":"2016-02-10 8","book title":"Small Town","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"SmallTownByPhilipK.Dick.pdf","pdf page count 1":"17","pdf country 1":"","pdf info 1":"Amazing Stories, May 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"687","publish date":"2016-02-10 8","book title":"Souvenir","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"SouvenirByPhilipK.Dick.pdf","pdf page count 1":"12","pdf country 1":"","pdf info 1":"Fantastic Universe, October 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"686","publish date":"2016-02-10 8","book title":"Strange Eden","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Strange_Eden","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"StrangeEdenByPhilipK.Dick.pdf","pdf page count 1":"16","pdf country 1":"","pdf info 1":"Imagination, December 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"685","publish date":"2016-02-10 8","book title":"Survey Team","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"SurveyTeamByPhilipK.Dick.pdf","pdf page count 1":"12","pdf country 1":"","pdf info 1":"Fantastic Universe, May 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"684","publish date":"2016-02-10 8","book title":"Mr. Spaceship","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Mr._Spaceship","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"Mr.SpaceshipByPhilipK.Dick.pdf","pdf page count 1":"26","pdf country 1":"","pdf info 1":"Imagination, January 1953","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"683","publish date":"2016-02-10 8","book title":"Of Withered Apples","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"OfWitheredApplesByPhilipK.Dick.pdf","pdf page count 1":"8","pdf country 1":"","pdf info 1":"Cosmos, July 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"682","publish date":"2016-02-10 8","book title":"Tony And The Beetles","book author":"Philip K. Dick","story link on wikipedia":"","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TonyAndTheBeetlesByPhilipK.Dick.pdf","pdf page count 1":"12","pdf country 1":"","pdf info 1":"Orbit, No. 2, 1953","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"681","publish date":"2016-02-10 8","book title":"The Turning Wheel","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Turning_Wheel","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheTurningWheelByPhilipK.Dick.pdf","pdf page count 1":"22","pdf country 1":"","pdf info 1":"Science Fiction Stories, 2, 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"680","publish date":"2016-02-10 8","book title":"The Unreconstructed M","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Unreconstructed_M","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheUnreconstructedMByPhilipK.Dick.pdf","pdf page count 1":"40","pdf country 1":"","pdf info 1":"Science Fiction Stories, January 1957","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"679","publish date":"2016-02-10 8","book title":"Upon The Dull Earth","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/Upon_the_Dull_Earth","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"UponTheDullEarthByPhilipK.Dick.pdf","pdf page count 1":"25","pdf country 1":"","pdf info 1":"Beyond Fiction, Volume 2, Number 3, Issue 9 (1954)","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"678","publish date":"2016-02-10 8","book title":"The Variable Man","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/The_Variable_Man","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"TheVariableManByPhilipK.Dick.pdf","pdf page count 1":"69","pdf country 1":"","pdf info 1":"Space Science Fiction, September 1953","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""},

	{"episode number":"677","publish date":"2016-02-10 8","book title":"A World Of Talent","book author":"Philip K. Dick","story link on wikipedia":"http://en.wikipedia.org/wiki/A_World_of_Talent","author wikipedia entry":"https://en.wikipedia.org/wiki/Philip_K._Dick","pdf link 1":"AWorldOfTalentByPhilipK.Dick.pdf","pdf page count 1":"42","pdf country 1":"","pdf info 1":"Galaxy Science Fiction, October 1954","pdf link 2":"","pdf page count 2":"","pdf country 2":"","pdf info 2":"","pdf link 3":"","pdf page count 3":"","pdf country 3":"","pdf info 3":"","pdf link 4":"","pdf page count 4":"","pdf country 4":"","pdf info 4":""}




	]

module.exports = pdf_pkd;



